import os

# 全局配置
DURATION = 5
TRANSITION = 1
MAX_IMAGES = 2
PROGRESS_BAR_HEIGHT = 5
THREAD_POOL_SIZE = 4
THUMBNAIL_SIZE = (500, 500)
DEFAULT_FOLDER = os.path.abspath("./img")
MEMORY_MONITORING = True
